### PR TITLE
Add Content Store

### PR DESCRIPTION
**Pull request by Pairarma**
This adds a Content Store to ndn-lite, the functionality is similar to the NFD Developer’s Guide and works as follows:

- when satisfying an interest, the data packet is saved in an additional CS nametree. The nametree is similar to the FIB or PIT nametree `(/forwarder/cs.*)`
- the Incoming Interest pipeline checks for a prefix match in the CS and satisfies the interest without creating an entry in the PIT
- when trying to add entries into a full CS then not-fresh entries or the oldest entry will be deleted
- the freshness Period and content of a CS entry will be updated when receiving same interests again
- the CS policy is FIFO implemented with a double linked list `(/util/dll.*)`
- unlike the NFD Guide, the Content Store lookup is before the inserting a PIT in the Incoming Interest pipeline
- additional tests are added for the unit tests `(/tests/unit-tests/forwarder/forwarder-tests.c)`
- the CS is not a modular component yet, but reserves memory the same way as done for FIB and PIT

The first few commits fix some compiler warnings, since PR #86 has not been merged yet.

### CODE REVIEW

**Comment by Pairarma** [comment]
The size of the Content Store should be smaller than the FIB or PIT because it has less entries and the memory is reserved the same way in `/forwarder/forwarder.h`.
I couldn't check it with a board yet, but running the unit-tests with valgrind with a maximum of 10 CS entries allocates approximately 10 KB.
Is there a better way to tell you how much RAM is needed for the Content Store?

**Comment by yoursunny** [comment]
> a maximum of 10 CS entries allocates approximately 10 KB.

I think this makes sense.

**Comment by Pairarma** [comment]
@tianyuan129 Can you please review this PR so we can merge it into master?

**Comment by yoursunny** [comment]
> @tianyuan129 Can you please review this PR so we can merge it into master?

I think #86 should merge before this?

**Comment by Pairarma** [comment]
> > @tianyuan129 Can you please review this PR so we can merge it into master?
> 
> I think #86 should merge before this?

Yes, that would be great. As mentioned before, the first few commits are the same as in #86.

**Comment by tianyuan129** [comment]
I think this PR makes a lot of sense in completing the functionality of the forwarder. Thank you for the contribution! We did think about adding CS and worried about the memory footprint. 10K is a fairly reasonable number.

I'm think about if we should enable user determining whether to include the CS or not at compile time. It's an open question to discuss. The current PR is already great to merge.

**Comment by Pairarma** [comment]
> I'm also thinking about if we should enable users determining whether to include the CS or not at compile time. It's an open question to discuss. The current PR is already great to merge.

That sounds like a great idea, but maybe we can take care about it at a later time.
We want to carry on using ndn-lite containing a CS for other contributions (like for RIOT) as an external package, but that first requires it to be available in your repository.

I also now merged PR #86 with this PR with the last commit (0d4c733), so this PR should also be ready to merge.

**Comment by tianyuan129** [comment]
Sounds great! Merged.

**Pull request merged**
